### ISSUE TITLE
Bug: truncated actionbar and FAB when stopping to scroll

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mzgreen/HideOnScrollExample#9] opened 2015-08-19 06:32 UTC
I'd like to have it like on the play Store : 
if you stop touching the screen, the action bar will never be half-shown, but always animate to hidden/shown if needed.
Not only that, but I got the FAB being truncated this way.

on this sample (part 3), I can see this happening :
![device-2015-08-19-093222](https://cloud.githubusercontent.com/assets/5357526/9349996/3fce25b8-4655-11e5-854f-7eaa2b16084a.png)

**Comment by ShreyashPromact** [comment] 2015-08-19 07:37
@AndroidDeveloperLB 

Yes there is problem in Part3. But you can use part2 for same effect. In part2 it is working fine as you want.

Sincerely,
Shreyash

**Comment by AndroidDeveloperLB** [comment] 2015-08-19 07:43
Please check how it works on the Play Store. 
When starting the app, I can scroll a bit down, and the content will scroll a bit, yet the action bar will always animate to a logical place.
Even on Part 2, I can see issues related to it. See what I've managed to do :

![device-2015-08-19-104226](https://cloud.githubusercontent.com/assets/5357526/9351092/06d4205a-465f-11e5-88b0-c59ef770a38a.png)

Anyway, please advice on what should be done. You can also show it here to get bounty:
http://stackoverflow.com/q/31990108/878126

**Comment by mzgreen** [comment] 2015-08-19 08:35
As I have mentioned in the post it's how Design Support Library works. There is an issue in Android's bugtracker so I think it will be fixed in the future. As for now I think that it should be possible to create a custom Behavior for this.

**Comment by kientux** [comment] 2015-09-20 18:42
With Support Library version 23 the problem is gone. Actually it's not only the floating button is truncated, but the bottom view will be truncated. If someone can't upgrade to v23 support library (compability reason), just set `layout_marginBottom="?attr/actionBarSize"` to bottom view.

**Comment by AndroidDeveloperLB** [comment] 2015-09-20 19:02
@kientux what bottom view? the last item of the RecyclerView ?

**Comment by kientux** [comment] 2015-09-20 19:12
@AndroidDeveloperLB it's the last view in CoordinatorLayout. But I just check again, the problem is still there with v23 library. And marginBottom didn't work as expected. Maybe you should use part 2 and wait for Google to fix this.

**Comment by kientux** [comment] 2015-09-20 19:18
Or you can take a look at this SO answer: http://stackoverflow.com/a/31140112/4405051

**Comment by AndroidDeveloperLB** [comment] 2015-09-20 19:34
@kientux Is this bug reported somewhere here: https://code.google.com/p/android/issues/ ?

**Comment by kientux** [comment] 2015-09-21 03:13
@AndroidDeveloperLB I think it's here: https://code.google.com/p/android/issues/detail?id=177195

I just clone latest version of this repo and have no problem at all. Still finding a difference between my code and @mzgreen 's code :l

**Comment by mzgreen** [comment] 2016-05-10 13:37
Use newest support lib and it should work fine.

**Closed as completed by mzgreen** 2016-05-10 13:37 UTC
